# nonk8s
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: spark-on-k8s
build:
  local:
    useBuildkit: false
    concurrency: 1
  tagPolicy:
    sha256: {}
  artifacts:
  - image: spark-base-image
    context: images/base-images/spark-base-image
    docker:
      buildArgs:
        SPARK_VERSION: 3.5.0
  - image: spark-app-example
    context: images/custom-images/spark-app-example

profiles:
- name: dev
  deploy:
    kustomize:
      paths:
      - deployment/overlays/dev
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      image: spark-submit-job
      context: services/spark-submit-job
      requires:
      - image: spark-base-image
        alias: SPARK_BASE_IMAGE
      - image: spark-app-example
        alias: SPARK_APP_EXAMPLE_IMAGE
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: s3
      context: services/s3
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: spark-history-server
      context: services/spark-history-server
      requires:
      - image: spark-base-image
        alias: SPARK_BASE_IMAGE
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: spark-reverse-proxy
      context: services/spark-reverse-proxy
      docker:
        target: RUNTIME

- name: prod
  deploy:
    kustomize:
      paths:
      - deployment/overlays/prod
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      image: spark-submit-job
      context: services/spark-submit-job
      requires:
      - image: spark-base-image
        alias: SPARK_BASE_IMAGE
      - image: spark-app-example
        alias: SPARK_APP_EXAMPLE_IMAGE
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: s3
      context: services/s3
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: spark-history-server
      context: services/spark-history-server
      requires:
      - image: spark-base-image
        alias: SPARK_BASE_IMAGE
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: spark-reverse-proxy
      context: services/spark-reverse-proxy
      docker:
        target: RUNTIME
