# nonk8s
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: spark-on-k8s
build:
  local:
    useBuildkit: false
    concurrency: 2
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: spark-base-image
    context: images/base-images/spark-base-image
    docker:
      buildArgs:
        SPARK_VERSION: 3.5.0
  - image: spark-app-example
    context: images/custom-images/spark-app-example
  - image: ui-reverse-proxy
    context: images/custom-images/ui-reverse-proxy

profiles:
- name: batch
  deploy:
    kustomize:
      paths:
      - deployment/overlays/dev
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      image: sparkhs
      context: services/sparkhs
      requires:
      - image: spark-base-image
        alias: SPARK_BASE_IMAGE
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: spark-reverse-proxy
      context: services/spark-reverse-proxy
      requires:
      - image: ui-reverse-proxy
        alias: REVERSE_PROXY_IMAGE
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: s3
      context: services/s3
      docker:
        target: RUNTIME


- name: airflow
  deploy:
    kustomize:
      paths:
      - deployment/overlays/dev
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      image: sparkhs
      context: services/sparkhs
      requires:
      - image: spark-base-image
        alias: SPARK_BASE_IMAGE
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: spark-reverse-proxy
      context: services/spark-reverse-proxy
      requires:
      - image: ui-reverse-proxy
        alias: REVERSE_PROXY_IMAGE
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: s3
      context: services/s3
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: airflow
      context: services/airflow
      docker:
        target: RUNTIME

- name: dev
  deploy:
    kustomize:
      paths:
      - deployment/overlays/dev
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      image: sparkhs
      context: services/sparkhs
      requires:
      - image: spark-base-image
        alias: SPARK_BASE_IMAGE
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: spark-reverse-proxy
      context: services/spark-reverse-proxy
      requires:
      - image: ui-reverse-proxy
        alias: REVERSE_PROXY_IMAGE
      docker:
        target: RUNTIME
  - op: add
    path: /build/artifacts/-
    value:
      image: s3
      context: services/s3
      docker:
        target: RUNTIME
