apiVersion: batch/v1
kind: Job
metadata:
  name: init-bucket-job
spec:
  template:
    spec:
      containers:
      - name: init-bucket-job
        image: s3
        command: ["/entrypoint", "init"]
        env:
        - name: PORT
          value: "9000"
        - name: ENDPOINT_URL
          value: s3
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secrets
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secrets
              key: S3_SECRET_KEY
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: s3-secrets
              key: S3_BUCKET_NAME
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "12345678"
      restartPolicy: OnFailure
