apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
  labels:
    app: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      name: s3
      labels:
        app: s3
    spec:
      containers:
      - name: s3
        image: s3
        command: ["/entrypoint"]
        env:
        - name: PORT
          value: "9000"
        - name: CONSOLE_PORT
          value: "9001"
        - name: ENDPOINT_URL
          value: s3
        - name: MINIO_SERVER_URL
          value: http://s3:9000
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secrets
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secrets
              key: S3_SECRET_KEY
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: s3-secrets
              key: S3_BUCKET_NAME
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "12345678"
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: s3
spec:
  selector:
    app: s3
  ports:
  - protocol: TCP
    port: 9000
    name: s3-api

  - protocol: TCP
    name: console
    port: 9001
