apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  labels:
    app: spark-history-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      name: spark-history-server
      labels:
        app: spark-history-server
    spec:
      containers:
      - name: spark-history-server
        image: spark-history-server
      imagePullSecrets:
      - name: regcred
---

apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
spec:
  selector:
    app: spark-history-server
  ports:
  - protocol: TCP
    port: 18080
